### ISSUE TITLE
[Docs]: Write a contributing guide

### ISSUE THREAD

**Issue by suitupstan** [CeruleanCodersComm/.github#2]
### Description

Write a genuine contributing guide that works like a fallback for all the repos.

**Include Sections like**

- Reporting good bugs
- Reporting good feature requests
- Cloning the project & creating pr
- Branch naming convention (type-description-issueNo, ex: docs-contributing-guide-2)
- Commit message guideline (conventional commits)
- A small & concise reviewer guide
- Link to our community

### Anything else?

You can take inspiration from:

- [Atom Contributing Guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)
- [Web3Community Guide](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/CeruleanCodersComm/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DhansAL** [comment]
i'll take this

**Comment by suitupstan** [comment]
Sure @DhansAL 👍 Go for it 🚀

**Comment by Abhirv08** [comment]
@DhansAL  Are you working on this issue?

**Comment by DhansAL** [comment]
@Abhirv08 you can take it ^_^ it'll be a great help.

**Comment by suitupstan** [comment]
@Abhirv08 Do you wanna get assigned to this?

**Comment by Abhirv08** [comment]
@krishguptadev  sure.

**Comment by Abhirv08** [comment]
@krishguptadev please tell me what to write in  small & concise reviewer guide and please provide community link.

**Comment by suitupstan** [comment]
> @krishguptadev please tell me what to write in small & concise reviewer guide and please provide community link.

A reviewer guide should include things like how to review, how to suggest changes and more...

Community link: https://dsc.gg/ceruleancoders

**Comment by Abhirv08** [comment]
@krishguptadev I am not getting what to write in review section, please help me out.

**Comment by suitupstan** [comment]
> @krishguptadev I am not getting what to write in review section, please help me out.

Aight! You can write the rest of the guide, I'll write the reviewer guide.

**Comment by Abhirv08** [comment]
@krishguptadev Thank you

**Comment by sauradip007** [comment]
@krishguptadev is this issue been taken up?

**Comment by suitupstan** [comment]
@sauradip007 Sorry this has been already completed :D
